global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
    - job_name: 'sql_exporter'
      static_configs:
          - targets: ['localhost:9237']
    - job_name: 'nginx_exporter'
      static_configs:
          - targets: ['localhost:9113']